services:
  db:
    image: postgres:16-alpine
    container_name: reuel_pet_db
    environment:
      POSTGRES_USER: petuser
      POSTGRES_PASSWORD: petpassword
      POSTGRES_DB: reuel_pet_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: