services:
  app:
    build: ./backend
    container_name: reuel_pet_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d5kh2bur433s73ereapg-a.oregon-postgres.render.com/reuel_pet_shop_postgres_database
      - SPRING_DATASOURCE_USERNAME=reuel_pet_shop_postgres_database_user
      - SPRING_DATASOURCE_PASSWORD=3NKXP5udgM2CabGYkfCTTVCNHEmlNbAx

  frontend:
    build: ./frontend
    container_name: reuel_pet_frontend
    ports:
      - "3000:80"  # Maps your local port 3000 to Nginx port 80
    depends_on:
      - app